---
- name: Install MariaDB server and Python MySQL client
  apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: present

- name: Create /etc/mysql/mariadb.conf.d/99-openstack.cnf with configuration
  copy:
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    content: |
      [mysqld]
      bind-address = 10.0.0.11
      default-storage-engine = innodb
      innodb_file_per_table = on
      max_connections = 4096
      collation-server = utf8_general_ci
      character-set-server = utf8
    owner: root
    group: root
    mode: '0644'

- name: Ensure MariaDB service is started and enabled
  service:
    name: mariadb
    state: started
    enabled: yes
