---
- name: Install RabbitMQ server
  apt:
    name: rabbitmq-server
    state: present

- name: Enable the RabbitMQ management plugin
  command: rabbitmq-plugins enable rabbitmq_management

- name: Ensure RabbitMQ service is started and enabled
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Set permissions for the OpenStack user
  command: rabbitmqctl set_permissions openstack ".*" ".*" ".*"
  when: ansible_os_family == "Ubuntu"
