---
- name: Install Memcached and Python Memcache client
  apt:
    name:
      - memcached
      - python3-memcache
    state: present

- name: Configure Memcached to listen on the management IP address
  lineinfile:
    path: /etc/memcached.conf
    regexp: '^-l'
    line: '-l 10.0.0.11'
    state: present

- name: Ensure Memcached service is started and enabled
  service:
    name: memcached
    state: started
    enabled: yes
